#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALAngular
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AngularBDD")]
	public partial class dbAngularDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public dbAngularDataContext() : 
				base(global::DALAngular.Properties.Settings.Default.AngularBDDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbAngularDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAngularDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAngularDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbAngularDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminaMunicipio")]
		public int spEliminaMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pidMunicipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pidMunicipio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertaMunicipio")]
		public int spInsertaMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pidEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pdesMunicipio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> presultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pidEstado, pdesMunicipio, presultado);
			presultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListaMunicipioByEstados")]
		public ISingleResult<spListaMunicipioByEstadosResult> spListaMunicipioByEstados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> pidEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pidEstado);
			return ((ISingleResult<spListaMunicipioByEstadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spModificaMunicipio")]
		public int spModificaMunicipio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pidMunicipio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pdescripcionMunicipio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pidMunicipio, pdescripcionMunicipio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListaEstado")]
		public ISingleResult<spListaEstadoResult> spListaEstado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spListaEstadoResult>)(result.ReturnValue));
		}
	}
	
	public partial class spListaMunicipioByEstadosResult
	{
		
		private int _idMunicipio;
		
		private int _idEstado;
		
		private string _Descripcion;
		
		public spListaMunicipioByEstadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipio", DbType="Int NOT NULL")]
		public int idMunicipio
		{
			get
			{
				return this._idMunicipio;
			}
			set
			{
				if ((this._idMunicipio != value))
				{
					this._idMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstado", DbType="Int NOT NULL")]
		public int idEstado
		{
			get
			{
				return this._idEstado;
			}
			set
			{
				if ((this._idEstado != value))
				{
					this._idEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class spListaEstadoResult
	{
		
		private int _idEstado;
		
		private string _Descripcion;
		
		private string _fotoEstadoUrl;
		
		public spListaEstadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstado", DbType="Int NOT NULL")]
		public int idEstado
		{
			get
			{
				return this._idEstado;
			}
			set
			{
				if ((this._idEstado != value))
				{
					this._idEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotoEstadoUrl", DbType="VarChar(150)")]
		public string fotoEstadoUrl
		{
			get
			{
				return this._fotoEstadoUrl;
			}
			set
			{
				if ((this._fotoEstadoUrl != value))
				{
					this._fotoEstadoUrl = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
